### PR TITLE
Change from aioredis to hiredis, update to pydantic v2

### PR DESCRIPTION
**Pull request by pabdavis**
Hello, I wanted to use this within a project, so I updated a few of the packages.

### CODE REVIEW

**Review by roma-glushko — APPROVED** [review]
This is awesome, Bill 👍

**Comment by roma-glushko** [comment]
Will take a look at the tests to fix the failures. They don't seem to be connected to the PR.

**Comment by pabdavis** [comment]
Attempted to update the test github action (not tested thou)

**Comment by roma-glushko** [comment]
Perfect Bill 👍 Merging the PR and will make sure this change is published as a new PyPi version.

**Comment by roma-glushko** [comment]
The new version of the emitter has just published under v0.0.3 🎉 
https://pypi.org/project/socket.io-redis-emitter/0.0.3/

**Pull request merged**
